### ISSUE TITLE
Convert to use 'Processing Framework'

### ISSUE THREAD

**Issue by ApneaCTB** [ptarroso/layer2kmz#12]
Hey,

Wondering if you could please convert the plugin to use the 'Processing Framework' so I can use it in the Graphical Modeler? I tried but i've got lost in the code (Python newb).

Cheers,
Stu

**Comment by ptarroso** [comment]
Hi!
I did consider that but, to be honest, I never had a deep look into how to implement a processing plugin. It is a possibility for a future version, especially if it allows the two frameworks to coexist.

**Comment by ApneaCTB** [comment]
Thanks for the consideration.

I was trying to follow along with this guide, that appears to change from a standard plugin to the processing version: [Link](https://courses.spatialthoughts.com/pyqgis-in-a-day.html#processing-scripts)

**Comment by ptarroso** [comment]
@ApneaCTB There is a new branch named "processing" in the repository. There you can find a functional version with processing support. I just finished porting it and couldn't do exhaustive testing. If you want to try it you have to manually install in your computer. If you do try, please send some feedback of errors that you might encounter.

**Comment by ApneaCTB** [comment]
Amazing :) I will give it a go later today with some of my data and let you know.

**Comment by ApneaCTB** [comment]
So it appears to load a run. I got this Warning:
![image](https://user-images.githubusercontent.com/44367799/81683123-069bc380-9499-11ea-8941-cf407e7e6024.png)

It ask for a 'Folder field' but I don't understand the intent. Appears I can just put any string in there and is happy:
![image](https://user-images.githubusercontent.com/44367799/81683537-90e42780-9499-11ea-86c8-ffd17ed4af94.png)
The save dialog seems to want the .kmz extension but is added when written:
![image](https://user-images.githubusercontent.com/44367799/81683962-e9b3c000-9499-11ea-9776-d6ca38e54d4c.png)

It doesn't seem to output a kmz file although it seems like it did according to the logs:
![image](https://user-images.githubusercontent.com/44367799/81684421-4ca55700-949a-11ea-8a0f-0ad16e30e3f3.png)

Love your work @ptarroso :)

**Comment by ptarroso** [comment]
Thanks for the feedback, @ApneaCTB !
1. Warning is corrected now
2. The folder field is the grouping of placemarks in kmz accodingly to a field in the data. It is much easier to turn on and off a group of features in GEarth when you have lots of data but organized in folders. It should be a field of your attribute table. So a string should be fine if it corresponds to a field. 
3. File extension is corrected
4. Maybe it is related to the field folder? My is exporting correctly and I can't reproduce this behavior... I have used this model (basically a duplication of inputs for layer to kmz):
![test](https://user-images.githubusercontent.com/11311876/81699336-18f90b80-945f-11ea-8f6f-a4d10fbf9b47.png)

(export, label and folder are "Vector Fields" inputs)

**Comment by ApneaCTB** [comment]
Thanks for including that diagram. I simplified mine and recreated the same as what you provided. Initially it wasn't outputting a file but then I disabled the other versions of the plugin and restarted QGIS then it output a file. 
When opening the file the locations are all set to the north pole (No coordinate data in the lat long fields). Inspecting the kmz file in notepad, it shows the UTM coords but not the grid. I assume this may be the same thing as discussed in #11 .

**Comment by ApneaCTB** [comment]
I kinda got around the issue by reprojecting the layer to WGS 84, I lose the symbology but that's ok for my use:
![image](https://user-images.githubusercontent.com/44367799/81757726-29fb5880-9503-11ea-8c50-a21ff3e4abf5.png)

**Comment by PedroVenancio** [comment]
@ApneaCTB if you have the vector layer style in QML, you can use 'Set layer style' algorithm in the model, after the reproject.

**Comment by ptarroso** [comment]
Thanks @PedroVenancio for the solution! It is almost perfect! It is automated and does not require coordinate transformation to be performed bay layer2kmz. The only problem I found is that the user needs to save the style to a file before using the model. This limits a bit the automation... I couldn't find a processing tool that would save the style of a file (I admit that my knowledge on the available processing tools is rather limited) so I added the tool to the layer2kmz (it is in fact a single line of code...). I think it solves the problem of @ApneaCTB  and #11.

**Comment by ptarroso** [comment]
here is the model that could be used:
![model](https://user-images.githubusercontent.com/11311876/81859819-be92a480-955d-11ea-81ff-4215f43f32b8.png)
It saves the style and opens it again. Maybe not the most beautiful solution, but it does work! Reproject in the model allows to get CRS from the project, so it is a solution to #11.

**Comment by PedroVenancio** [comment]
Olá Pedro!

This works like a charm!!!

I've made a PR just to fix small issues: https://github.com/ptarroso/layer2kmz/pull/13

I also had changed a little bit your model to:

![Export_to_KMZ](https://user-images.githubusercontent.com/1331581/81877154-4d161e80-957c-11ea-8ecc-08f4b2c4cea2.png)

1. I simply added a Boolean input parameter to have the option to show or hide labels in the model;
2. I added the Multipart to singleparts algorithm to ensure that none of the geometries are multi;
3. I added the Rename layer algorithm, to ensure that the original Vector layer name is preserved in GoogleEarth     <Document> <name> and <Schema id="" name=""> tags, with an expression ( layer_property(@vectorlayer, 'name') ).

Here is the complete model, that I think cover all parts to completely automate the plugin:

[Export_to_KMZ_model.zip](https://github.com/ptarroso/layer2kmz/files/4625265/Export_to_KMZ_model.zip)

and it is amazing to see it running as batch, exporting all project layers to kmz at once! :)

![imagem](https://user-images.githubusercontent.com/1331581/81877521-39b78300-957d-11ea-8a3c-922429967d1c.png)

Two questions now:

1. When I try to convert polygon layers, I get this error message:
`Error: local variable 'poly' referenced before assignment`
I've done few tests. Can you confirm? Should I open a new ticket?

2. Is there any possibility to the plugin work with the layers switched off in QGIS canvas?

Thank you very much for the plugin and for the recent integration on Processing! It opens a bunch of new possibilities!

**Comment by ptarroso** [comment]
@PedroVenancio Thanks a lot! I already merged your commits. Thanks also for the model!
In relation to your questions:
1- Yes, open a new issue with that
2 - I'll have to check the code

**Comment by ApneaCTB** [comment]
This is amazing. I'm new to a lot of the GIS world, so I will digest the above an try with my own project. 

I would actually like to have the ability to export a few other formats(GPX, KML) through the modeler, but that's outside of this scope :)

Thanks for your work and responses.
