### ISSUE TITLE
Local variable 'poly' referenced before assignment

### ISSUE THREAD

**Issue by PedroVenancio** [ptarroso/layer2kmz#14]
Hi @ptarroso 

This error happens with every polygon conversion

`2020-05-16T01:21:40     CRITICAL    Error : local variable 'poly' referenced before assignment`

To replicate, just load or create a new shapefile and try to export2kmz.

Thanks!

**Comment by ptarroso** [comment]
@PedroVenancio It is corrected now in master and processing branches

**Comment by PedroVenancio** [comment]
Great @ptarroso !

Tested here and it is fixed!

Thank you very much!
