### ISSUE TITLE
Symbology 

### ISSUE THREAD

**Issue by styfler** [ptarroso/layer2kmz#2]
Hi there,

Thank you so much for the tool! It is just what I was looking for.

My QGIS version is 2.18..0 and I am having a problem when it comes to the categorized symbology. I'm putting a symbology on my layer but it is not going to the Google Earth. How should I apply the categorized symbology in order that it could go to GE?

Thank you!

**Comment by ptarroso** [comment]
Hi

Thank you very much for your interest and nice words! I'm sorry that the plug in is not working as expected, but thanks for your feedback that will surely help to improve it. 

I would need, however, some more details on your data and error. Do you have a point, line or polygon layer? Does it export something to GE or does it create an empty kmz? Does it give you any error in QGIS? Can you replicate the error with some random data that you could share? That would be perfect to test the plugin. 

The plugin should be very straightforward to use: open your layer, select a categorized symbology (based in one of the fields, for example), and export to kmz...
