### ISSUE TITLE
Style None throws exception...

### ISSUE THREAD

**Issue by zeddock** [ptarroso/layer2kmz#3]
At 50% processing, I get an exception:

 File "C:/Users/jim/.qgis2/python/plugins\layer2kmz\kml.py", line 186, in addPlacemark
			    "placemark using it." % (style))
			Exception: Style None must be added before a placemark using it.

**Comment by ptarroso** [comment]
Thanks for your interest in the plugin and the feedback!

That error is likely occurring because you have features in your data that without symbology (maybe they are meant to be hidden and not displayed in the map). The plugin assumes that all features in the layer are to be exported to kmz and fails when it reaches a feature without symbology. I'll check the code to try to filter out features without symbols. Meanwhile, a possible workaround would be to export to a new layer only those features with symbols and then export to kmz. 

let me know if that was the problem!

**Comment by zeddock** [comment]
Hi Pedro.

I just got finished sending you an email on this. Please take a look and
let me know how I can help or what I can do to start testing and fixing?

Thanx!

Jim

*     Jim*Garner  *304-933-9858*
*   www.Ground*Scouts.com

**Comment by zeddock** [comment]
I tested as you suggest. Unless I misunderstood, every feature had a
polygon symbol.  I will try to do a very small subset of the layer to see
if that fails, but I can guess it will.  I will wait for you to look at the
other email I sent to you to see if it gives you any insight.

My first guess was because of the JOIN being used, since that is not really
a standard approach.

Jim

*     Jim*Garner  *304-933-9858*
*   www.Ground*Scouts.com

**Comment by zeddock** [comment]
I attempted a SMALL portion of features, without any specific symbology.
It hit THIS error:

IndexError: list index out of range

Traceback (most recent call last):
  File "C:/Users/jim/.qgis2/python/plugins\layer2kmz\layer2kmz.py",
line 224, in run
    kmlproc.process()
  File "C:/Users/jim/.qgis2/python/plugins\layer2kmz\layer2kmz.py",
line 374, in process
    Kml.addPlacemark(folder, name, style, coords, fields)
  File "C:/Users/jim/.qgis2/python/plugins\layer2kmz\kml.py", line
226, in addPlacemark
    if isinstance(coords[0], tuple):
IndexError: list index out of range


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit
(AMD64)]
QGIS version: 2.18.7 Las Palmas, 3b30e6a

I will start to eliminate weird things like the HTML anchors in the fields.

Jim

*     Jim*Garner  *304-933-9858*
*   www.Ground*Scouts.com

**Comment by zeddock** [comment]
FYI:

I have continued to significantly take things out of the layer to see when
it would start to work, but I keep hitting this now:

File "C:/Users/jim/.qgis2/python/plugins\layer2kmz\kml.py", line 226, in
addPlacemark

if isinstance(coords[0], tuple):

IndexError: list index out of range


I do not understand what this means, but I have a few more options to
explore.

*     Jim*Garner  *304-933-9858*
*   www.Ground*Scouts.com

**Comment by zeddock** [comment]
OK. This may be a part of the problem....

When I brought the layer in, I set it up to be a GEOPACKAGE.  Not and ESRI
Layer.

I have changed that, but I am still on the index error:

2017-06-09T13:09:10 1 Traceback (most recent call last):

File "C:/Users/jim/.qgis2/python/plugins\layer2kmz\layer2kmz.py", line 224,
in run

kmlproc.process()

File "C:/Users/jim/.qgis2/python/plugins\layer2kmz\layer2kmz.py", line 374,
in process

Kml.addPlacemark(folder, name, style, coords, fields)

File "C:/Users/jim/.qgis2/python/plugins\layer2kmz\kml.py", line 226, in
addPlacemark

if isinstance(coords[0], tuple):

IndexError: list index out of range


Below see the VERY limited area and fields involved with this.  **I just
don't understand what INDEX is being troublesome.  Can you help me identify
that please?



[image: Inline image 1]

*     Jim*Garner  *304-933-9858*
*   www.Ground*Scouts.com

**Comment by zeddock** [comment]
Pedro!

I found ONE problem!

I do not know what this is called in correct GIS terms, but whenever a
polygon feature is part of the layer which is separated into 2 parts, there
is this INDEX error.

Here is a picture of what I narrowed down.
[image: Inline image 1]


*     Jim*Garner  *304-933-9858*
*   www.Ground*Scouts.com

**Comment by ptarroso** [comment]
Using the 'multipart to singlepart' tool in the QGIS' vector menu solved this problem.
