### ISSUE TITLE
kmz does not open in the right place

### ISSUE THREAD

**Issue by izavicentini** [ptarroso/layer2kmz#4]
Hi! Thank you so much for your effort in creating this plugin. 
I am having some problems with the layers I try to export. They are all referenced to WGS84 zones 24M and 25M (northeast of Brazil) but when exported to GE the kmz file takes the view to the north pole and although the folders are in the kmz file the features do not appear on the surface.
I do not know if I am missing any steps in using this tool so I decided to ask for your help.
I am using Qgis 2.18.11. I am sending an atttached file of the view
![error_ge](https://user-images.githubusercontent.com/32675782/31389772-72a492c6-ada8-11e7-8e36-8dba5dbfa860.jpg)

**Comment by ptarroso** [comment]
Ola! 

Great that you like the plugin. Thanks for the feedback! 
I believe that the problem you are describing is related only to the coordinate system. Google earth is expecting plain lat long WGS84 coordinates and you are providing UTM coords (the 24M and 25M zones). The plugin does not do any coordinate conversion: it expects data in the correct CRD for the GEarth. So, my suggestion is: convert your data to WGS84 (EPSG:4326) and export the new data to kmz (in Qgis you can easily save transformed vector data in another CRD by right clicking in the layer name and chose "save as"). 

Can you try that please and let me know if it worked? 
Cheers

**Comment by izavicentini** [comment]
Hi! Thank you so much for answering so fast. It worked after doing as you said and I already passed the information to my coworkers and now we will be using your plugin to the fullest.
Thanks again!

**Comment by ptarroso** [comment]
I'm glad it worked! Thanks for using layer2kmz!
