### ISSUE TITLE
GE displays paths in attributes 

### ISSUE THREAD

**Issue by GrantOB** [ptarroso/layer2kmz#5]
Gidday,
Great easy to use tool.

I have noticed that when a kmz is saved in GE it changes the way the attributes are displayed. I have attached two screen shots the first 'capture_temp_places.png' is great just the way it should be, but then when I save the kmz to myplaces, file extensions appear in the attributes, which ain't so good, any thoughts on what is happening here? I do not get the same issue when I make the kmz via arcgis

![capture_myplaces](https://user-images.githubusercontent.com/25045406/34856988-431ea920-f7ad-11e7-82d7-f1a2da0af738.PNG)
![caputre_temp_places](https://user-images.githubusercontent.com/25045406/34856989-435ed70c-f7ad-11e7-96ca-2373834b93d2.PNG)

next up (sorry there is more), is when I take use the kmz on mobile device all the symbology is lost, again the kmz saved via arcgis does not have this issue.

many thanks, we appreciate the work that goes in to these tools!
QGIS 2.18.12
windows 10

PS looks like the images are being displayed in inverse order

**Comment by ptarroso** [comment]
Hi 

Thank you for your interest in the plug and for the nice words! 

I'm sorry, but I'm not able to reproduce your error... I have created some data points randomly in QGIS, added a few attributes and three different symbols. The resulting kmz works pretty well in GEarth, even if I save it to my places. I don't know what mobile app you are using, but in Android Google Earth, the kmz works pretty well also. I'm sending my test.kmz file attached to see if you can reproduce the error. 

Please check that you are using the last versions of the plugin, GEarth and mobile app. Also, if you could send me a file where the error occurs and another where it doesn't (thar arcgis resulting kmz), it would be nice to compare. It would suffice a file with a single point (that APK9, for instance) if the problem persists with a single point. 

Please try with the attached file and let me know what happens! 

Cheers, 
Pedro 

[test.zip](https://github.com/ptarroso/layer2kmz/files/1625801/test.zip)

**Comment by tdrottner** [comment]
Hi,

First of all, thank you very much for creating this plugin as I use it on daily-basic and it saved me lots of time!!! You did great job.

However, I have same issue when saving KMZ to my places (**its when I have to do some edits to the files**), it will always display path to the KMZ file. I had a look on kml code itself and didnt see any suspicious (I am super beginner in any coding so this might be useless). If you only export data to GE it works fine though. 

Another things, although it is different issue/suggestion come up to me...
1) would it be possible to add "no label" option please? So far I had to edit kml file and remove <name> </name> 

2) when I export lines to GE, they never have same colour as I had in QGIS, for points its fine.

I had same issues on different machines (Win 8 and Win10), all QGIS 2.18.XX 

Thanks again for this plugin.
Tom

**Comment by ptarroso** [comment]
Hi
Thanks for the feedback and for using the plugin. 
I finally reproduce the problem reported with the exported kmz in GEarth. It seems that the problem is only visible after adding to my places and after restarting the GEarth... 

I have improved the style of the information balloon with a nice table. You can try the new code by downloading from this repository and replace the plugin in your QGIS plugin directory. The problem with line colors was also corrected by ATran31 (https://github.com/ptarroso/layer2kmz/pull/8#issue-220457102)

I will add the "no label" option later. However, as a workaround I suggest to add an empty field to your layer and use that field as label. 

all the best

**Comment by tdrottner** [comment]
Hi,

thank you for your quick response, will try it asap. However, for no label option, this workaround does not work as it always shows "NULL" text in Google Earth, which is not ideal. 

Thanks again.
Tom

**Comment by ptarroso** [comment]
Hi 

@tikos I have finally addressed this issue in the last version of the plugin. I did not upload it to qgis repository yet but the current version here in github has an option where you can turnoff label display.
