### ISSUE TITLE
Crash at 50% Processing

### ISSUE THREAD

**Issue by ozhamlet** [ptarroso/layer2kmz#7]
Python Error:
2018-04-13T11:18:30	1	Traceback (most recent call last):
			  File "C:/Users/David/.qgis2/python/plugins\layer2kmz\layer2kmz.py", line 224, in run
			    kmlproc.process()
			  File "C:/Users/David/.qgis2/python/plugins\layer2kmz\layer2kmz.py", line 401, in process
			    Kml.addPlacemark(folder, name, style, coords, fields)
			  File "C:/Users/David/.qgis2/python/plugins\layer2kmz\kml.py", line 238, in addPlacemark
			    if isinstance(coords[0], tuple):
			IndexError: list index out of range

Possibly due to size of shape file (2.8MB)

**Comment by ptarroso** [comment]
Hi 

Thanks for using the plugin! 

I don't think the size of the shapefile would generate that error. The most common cause of error is related to have multipart features. Try to run the tool "multipart to singleparts" found in the Vector -> Geometry Tools menu. Then run the plugin again to convert the resulting file to kmz. 

Please let me know if it worked!

**Comment by ozhamlet** [comment]
Pedro, thanks for the prompt reply.  I tried your suggestion and
layer2kmz did not crash.  However, the resulting KMZ isn't quite
complete.  Here are the steps I took:
Original SHP file:
 
After Mulitpart > Single part (I guess there's a way to recombine
these):
 
layer2kmz (I'm not sure what the 'Folder Field' field is for):
 
Resulting KMZ (there are no labels and the 2 largest electorates
are missing): 
Any tips appreciated.

David
--
David Letham
m: +61 439 821 767 
s: hamletd1
e: leg@fastmail.com



On Fri, 13 Apr 2018, at 5:40 PM, Pedro Tarroso wrote:
> Hi 
> 
>  Thanks for using the plugin! 
> 
>  I don't think the size of the shapefile would generate that error.
>  The most common cause of error is related to have multipart features.
>  Try to run the tool "multipart to singleparts" found in the Vector ->
>  Geometry Tools menu. Then run the plugin again to convert the
>  resulting file to kmz.> 
>  Please let me know if it worked! 
> 
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/ptarroso/layer2kmz/issues/7#issuecomment-381083008

**Comment by ptarroso** [comment]
After Mulitpart > Single part (I guess there's a way to recombine 
these): 

This tool just separate some features that are grouped together with the same attributes. The resulting file should have more features and duplicated lines in the attribute table from features that were separated. To group them together again, you can use the opposite tool 'Singleparts to multipart' (similar to the dissolve). But, maybe the best way is to preserve the original file :). 

layer2kmz (I'm not sure what the 'Folder Field' field is for): 

The 'Folder field' is to divide your data into folders. When using the KMZ with google earth, for instance, you can have the file and than a series of folders that group your data in a tree-like scheme. Sometimes is useful but to avoid it just create a field in your data where all features have the same value/string. Than it will be a single folder grouping your data (maybe I'll add this feature to the plugin later). 

Resulting KMZ (there are no labels and the 2 largest electorates 
are missing): 

Can you reproduce the error with other files? can you send me some screenshots that might illustrate the problem? In which program are you trying to check the kmz? Google Earth?
