### ISSUE TITLE
Plugin not visible in  3.4.10-Madeira QGIS 

### ISSUE THREAD

**Issue by dbpatni** [ptarroso/layer2kmz#9]
Hi Plugin not visible latest version of QGIS 3.4.10-Madeira
I have imported from zip file but QGIS saying  "This plugin is incompatible with this version of QGIS
Plugin designed for QGIS 2.0 - 2.99"

Please help.
![layer2kmz](https://user-images.githubusercontent.com/9840455/62821860-4693ea00-bb99-11e9-9580-83a03283ef71.JPG)

**Comment by ptarroso** [comment]
Hi 

Thank you for your interest! Yes, the current version is not compatible with the newest 3.x versions. I'm working on it and I will upload as soon as possible.

**Comment by ATran31** [comment]
Hey @ptarroso, have you started working on this yet? If not I could look into it.

**Comment by ptarroso** [comment]
Hi. I just finished a version that will be tagged as experimental. Check the qgis.v3 branch here that should be available now!

**Comment by ATran31** [comment]
I tried to install qgis.v3 branch via zip file but got the following error:
```Python
Couldn't load plugin 'layer2kmz-qgis.v3' 

ModuleNotFoundError: No module named 'layer2kmz-qgis' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 309, in loadPlugin
    __import__(packageName)
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'layer2kmz-qgis'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.4.12-Madeira Madeira, 625767347a 
```

**Comment by ptarroso** [comment]
Github is adding the branch name to the folder. Just rename the folder to "layer2kmz" otherwise QGIS won't find it.

**Comment by ATran31** [comment]
Fantastic. Everything appears to work as expected. Thanks for all your hard work and continued support for this plugin!

**Comment by ptarroso** [comment]
Thanks. It is also no in QGIS plug repository with experimental flag. You should be able to install it directly from the QGIS PlugIn Manager if you activate the experimental plugins option.
